### PR TITLE
Fix some error while initializing SDE server

### PR DESCRIPTION
**Pull request by aahameda**
Handled some exceptions due to empty groundtruths

### CODE REVIEW

**Comment by virajkarandikar** [comment]
Can you push this to NeMo main branch as well?

**Comment by virajkarandikar** [comment]
I think you will have to update submodule nemo commit also.

**Comment by aahameda** [comment]
> 



> Can you push this to NeMo main branch as well?

The changes made in this script are maglev specific right? Do we really need to push them to NeMo main branch?

**Comment by aahameda** [comment]
> 



> I think you will have to update submodule nemo commit also.

This needs to be done in [speech-mlops](https://gitlab-master.nvidia.com/jarvis/speech-mlops) repo, right?

**Pull request closed without merging**
